import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Poppins } from 'next/font/google'
import NavBar from "./components/navbar/Navbar"
import ClientOnly from "./components/ClientOnly"
import ContadorProvider from "./Context/ContadorProdutos"

const roboto = Roboto({
  weight: '700',
  subsets: ['latin'],
})

const poppins = Poppins({
  weight: '400', // Ajuste os pesos para incluir apenas os disponíveis
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClientOnly>
        <ContadorProvider>
          <NavBar />
        </ContadorProvider>
      </ClientOnly>
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
